version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login --username veselidrago --password Test1234?
         docker run -d --name db veselidrago/proprietary-db:1.2.3

     # build the application image
     - run: docker build -t veselidrago/nginx:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push veselidrago/nginx:$CIRCLE_BRANCH